service:
  id: "webitel-service-08"
  addr: "localhost:10159"
  conn:
    verify_certs: false


log:
  level: "info"
  otel: false
  console: true

postgres:
  dsn: "postgres://postgres:webitel@localhost:6432/webitel"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0


consul:
  addr: "localhost:8500"


pubsub:
  broker_url: "amqp://webitel:webitel@localhost:5673"
  broker_driver: "amqp"