// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageTypeText-0]
	_ = x[MessageTypeFile-1]
	_ = x[MessageTypeImage-2]
	_ = x[MessageTypeSystem-3]
}

const _MessageType_name = "MessageTypeTextMessageTypeFileMessageTypeImageMessageTypeSystem"

var _MessageType_index = [...]uint8{0, 15, 30, 46, 63}

func (i MessageType) String() string {
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
