// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageTypeUnknown-0]
	_ = x[MessageTypeText-1]
	_ = x[MessageTypeFile-2]
	_ = x[MessageTypeImage-3]
	_ = x[MessageTypeSystem-4]
	_ = x[MessageTypeInteractive-5]
	_ = x[MessageTypeLocation-6]
	_ = x[MessageTypeContact-7]
}

const _MessageType_name = "MessageTypeUnknownMessageTypeTextMessageTypeFileMessageTypeImageMessageTypeSystemMessageTypeInteractiveMessageTypeLocationMessageTypeContact"

var _MessageType_index = [...]uint8{0, 18, 33, 48, 64, 81, 103, 122, 140}

func (i MessageType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MessageType_index)-1 {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[idx]:_MessageType_index[idx+1]]
}
