// Code generated by "stringer -type=ThreadKind"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ThreadUnspecified-0]
	_ = x[ThreadDirect-1]
	_ = x[ThreadGroup-2]
	_ = x[ThreadChannel-3]
}

const _ThreadKind_name = "ThreadUnspecifiedThreadDirectThreadGroupThreadChannel"

var _ThreadKind_index = [...]uint8{0, 17, 29, 40, 53}

func (i ThreadKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ThreadKind_index)-1 {
		return "ThreadKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ThreadKind_name[_ThreadKind_index[idx]:_ThreadKind_index[idx+1]]
}
